name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-fastapi:${{ github.sha }}

  update-manifest:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests repository
        uses: actions/checkout@v3
        with:
          repository: ArleyGabriel06/hello-manifests
          token: ${{ secrets.GB_TOKEN }}
          
      - name: Atualizar imagem no YAML
        run: |
          sed -i 's|image: .*|image: '"${{ secrets.DOCKER_USERNAME }}"'/hello-fastapi:'"${{ github.sha }}"'|' deployment.yaml

      - name: Commit and push changes
        run: |
          git config user.name '${{ secrets.USER_NAME }}'
          git config user.email '${{ secrets.EMAIL_NAME }}'
          git add deployment.yaml
          git commit -m "Atualiza imagem para commit ${{ github.sha }}"
          git push
